on: [push]

jobs:
  security_check:
    runs-on: ubuntu-latest
    name: Check that security is all good
    steps:
      - name: Dependabot check
        id: dependabot
        uses: adriandersen/sec@v0.1
